### ISSUE TITLE
No such file or directory: 'adb'

### ISSUE THREAD

**Issue by tomtao2022** [Jekso/AndroidTV-Remote-Controller#1]
python3.13 testtv.py
💡 Starting ADB server...

Traceback (most recent call last):
  File "/Users/tomtao/Downloads/remotetv/AndroidTV-Remote-Controller-main/testtv.py", line 9, in <module>
    controller = AndroidTVController(ip)
  File "/Users/tomtao/Downloads/remotetv/AndroidTV-Remote-Controller-main/android_tv_rc/android_tv_controller.py", line 25, in __init__
    self.__adb_client = ADBClient(verbose, show_command)
                        ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomtao/Downloads/remotetv/AndroidTV-Remote-Controller-main/android_tv_rc/adb_client.py", line 57, in __init__
    self.start_server()
    ~~~~~~~~~~~~~~~~~^^
  File "/Users/tomtao/Downloads/remotetv/AndroidTV-Remote-Controller-main/android_tv_rc/adb_client.py", line 129, in start_server
    self.__server_process = self.__execute_command('start-server', blocking=False, include_selected_serial=False)
                            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomtao/Downloads/remotetv/AndroidTV-Remote-Controller-main/android_tv_rc/adb_client.py", line 111, in __execute_command
    return subprocess.Popen(command_parts, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 1966, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'adb'

**Comment by Jekso** [comment]
Hello, 
you can download platform_tools.
I already mention how to do it in the readme
and after that add the path of it into PATH Environment Variable, then restart your PC and start trying the connection again
